Add git-update golang based to dotfiles

diff --git a/home/bin/git/executable_git-update b/home/bin/git/executable_git-update
--- a/home/bin/git/executable_git-update
+++ b/home/bin/git/executable_git-update
@@ -1,55 +1,15 @@
 #!/usr/bin/env bash
-# SUMMARY: git-update will get the latest for your branch along with autostashing
-# replaces git-smart-pull
-set -eou pipefail
 
-source $HOME/bin/lib/common.sh
+# Script to run git-update.go
 
-readonly upstream_branch=$(git rev-parse --abbrev-ref --symbolic-full-name "@{u}")
-readonly default_branch="$(git branch-default)"
+set -euo pipefail
 
-readonly head_sha=$(git rev-parse HEAD)
+GO_FILE="$HOME/bin/bins/git-update/main.go"
 
-git_update_prettyprint_log () {
-  local format=$(
-    git config --get pretty.update ||
-    echo "%C(yellow)%h%Cblue%d%Creset %s - %C(white)%an %Cgreen(%cr)%Creset")
-
-  local merge_base_sha=$(git merge-base "$head_sha" "$remote_sha")
-  git log --format="$format" --graph "$merge_base_sha".."$remote_sha"
-}
-
-if [[ $(branch-name) != $default_branch ]]; then
-  header "Fetching origin $default_branch"
-  git fetch origin $default_branch:$default_branch --prune | indent
+# Check if the Go file exists
+if [ ! -f "$GO_FILE" ]; then
+    echo "Error: Go file not found at $GO_FILE"
+    exit 1
 fi
 
-header "Making sure we're tracking remote"
-git branch -u "origin/$(branch-name)" | indent
-
-header "Getting latest from remote on current branch"
-git pull --rebase=merges --autostash | indent
-
-remote_sha=$(git rev-parse "$upstream_branch")
-
-header "Changes applied"
-git_update_prettyprint_log
-success "✅ Complete"
-
-# Check the trunk branch
-hash1=$(git show-ref --heads -s origin/$default_branch)
-# Check the trunk branch vs the current
-hash2=$(git merge-base origin/$default_branch origin/HEAD)
-
-if [ "${hash1}" = "${hash2}" ];then
-  # No rebase/update needed
-  success "✅ No rebase needed to get current"
-else
-  echo "🆘 Rebase is required"
-  read -r -p "Continue? (Y/N): " confirm
-  if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
-    git rebase "origin/${default_branch}"
-  else
-    warn "Branch not current with origin/${default_branch}"
-  fi
-fi
+exec go run "$GO_FILE" "$@"
